import os
from datetime import datetime

from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table,
    TableStyle, HRFlowable, KeepTogether
)
from reportlab.graphics.shapes import Drawing, Rect, String
from reportlab.graphics.charts.barcharts import VerticalBarChart

home = os.path.expanduser("~")
onedrive_desktop = os.path.join(home, "OneDrive", "Desktop")
OUTPUT_DIR = onedrive_desktop if os.path.exists(onedrive_desktop) else os.path.join(home, "Desktop")

C_NAVY  = colors.HexColor("#1F3864")
C_BLUE  = colors.HexColor("#2E74B5")
C_BLUEL = colors.HexColor("#D6E4F0")
C_GREEN = colors.HexColor("#00B050")
C_GRN_B = colors.HexColor("#C6EFCE")
C_AMB_B = colors.HexColor("#FFEB9C")
C_RED_B = colors.HexColor("#FFC7CE")
C_GREY  = colors.HexColor("#F2F7FB")
C_WHITE = colors.white
C_BLACK = colors.HexColor("#1A1A1A")
C_MUTED = colors.HexColor("#7F7F7F")
C_BDR   = colors.HexColor("#BDD7EE")


def _ensure_output_dir():
    os.makedirs(OUTPUT_DIR, exist_ok=True)


def _styles() -> dict:
    return {
        "title":   ParagraphStyle("T",  fontName="Helvetica-Bold",    fontSize=22, textColor=C_NAVY,  spaceAfter=4,  alignment=TA_LEFT),
        "sub":     ParagraphStyle("S",  fontName="Helvetica",          fontSize=11, textColor=C_MUTED, spaceAfter=10, alignment=TA_LEFT),
        "section": ParagraphStyle("H",  fontName="Helvetica-Bold",    fontSize=13, textColor=C_BLUE,  spaceBefore=14,spaceAfter=6, alignment=TA_LEFT),
        "body":    ParagraphStyle("B",  fontName="Helvetica",          fontSize=10, textColor=C_BLACK, leading=16,    spaceAfter=8),
        "footer":  ParagraphStyle("F",  fontName="Helvetica-Oblique",  fontSize=8,  textColor=C_MUTED, alignment=TA_CENTER),
        "th":      ParagraphStyle("TH", fontName="Helvetica-Bold",    fontSize=9,  textColor=C_WHITE, alignment=TA_CENTER),
        "td":      ParagraphStyle("TD", fontName="Helvetica",          fontSize=9,  textColor=C_BLACK, alignment=TA_CENTER),
        "lbl":     ParagraphStyle("L",  fontName="Helvetica-Bold",    fontSize=9,  textColor=C_NAVY),
        "val":     ParagraphStyle("V",  fontName="Helvetica",          fontSize=9,  textColor=C_BLACK),
    }


def _header_footer(canvas, doc):
    canvas.saveState()
    w, h = A4
    canvas.setFillColor(C_NAVY)
    canvas.rect(0, h - 1.2*cm, w, 1.2*cm, fill=1, stroke=0)
    canvas.setFillColor(C_WHITE)
    canvas.setFont("Helvetica-Bold", 11)
    canvas.drawString(1.5*cm, h - 0.85*cm, "AI Desktop Workflow Agent")
    canvas.setFont("Helvetica", 9)
    canvas.drawRightString(w - 1.5*cm, h - 0.85*cm,
        datetime.now().strftime("Generated: %d %b %Y  %H:%M"))
    canvas.setStrokeColor(C_BLUE)
    canvas.setLineWidth(2)
    canvas.line(0, h - 1.25*cm, w, h - 1.25*cm)
    canvas.setStrokeColor(C_BDR)
    canvas.setLineWidth(0.5)
    canvas.line(1.5*cm, 1.0*cm, w - 1.5*cm, 1.0*cm)
    canvas.setFillColor(C_MUTED)
    canvas.setFont("Helvetica", 8)
    canvas.drawCentredString(w/2, 0.65*cm,
        f"Confidential  |  AI Desktop Workflow Agent  |  Page {doc.page}")
    canvas.restoreState()


def _info_table(s, task: str) -> Table:
    rows = [
        ("Report Date", datetime.now().strftime("%d %B %Y")),
        ("Task",        (task[:80]+"...") if len(task)>80 else task),
        ("Generated by","AI Desktop Workflow Agent"),
        ("Status",      "Completed"),
    ]
    data = [[Paragraph(k, s["lbl"]), Paragraph(v, s["val"])] for k, v in rows]
    t = Table(data, colWidths=[4*cm, 12.5*cm])
    t.setStyle(TableStyle([
        ("BACKGROUND",     (0,0),(0,-1), C_BLUEL),
        ("ROWBACKGROUNDS", (1,0),(1,-1), [C_WHITE, C_GREY]),
        ("GRID",           (0,0),(-1,-1), 0.4, C_BDR),
        ("VALIGN",         (0,0),(-1,-1), "MIDDLE"),
        ("LEFTPADDING",    (0,0),(-1,-1), 8),
        ("RIGHTPADDING",   (0,0),(-1,-1), 8),
        ("TOPPADDING",     (0,0),(-1,-1), 6),
        ("BOTTOMPADDING",  (0,0),(-1,-1), 6),
    ]))
    return t


def _data_table(s, excel_data: list[dict]) -> Table:
    STATUS_BG = {"done": C_GRN_B, "in progress": C_AMB_B, "pending": C_RED_B}
    # Reduce column widths to fit 9 columns on A4
    COL_W     = [1.2*cm, 3.2*cm, 2.0*cm, 2.0*cm, 1.6*cm, 1.8*cm, 1.8*cm, 1.4*cm, 2.5*cm]
    headers   = ["ID", "Task Name", "Owner", "Status", "Prio", "Start", "End", "%", "Notes"]
    header    = [Paragraph(h, s["th"]) for h in headers]
    rows      = [header]
    cmds      = [
        ("BACKGROUND",    (0,0),(-1,0), C_NAVY),
        ("GRID",          (0,0),(-1,-1), 0.4, C_BDR),
        ("VALIGN",        (0,0),(-1,-1), "MIDDLE"),
        ("LEFTPADDING",   (0,0),(-1,-1), 4),
        ("RIGHTPADDING",  (0,0),(-1,-1), 4),
        ("TOPPADDING",    (0,0),(-1,-1), 4),
        ("BOTTOMPADDING", (0,0),(-1,-1), 4),
    ]
    for i, row in enumerate(excel_data, 1):
        status = str(row.get("status",""))
        bg     = C_GREY if i % 2 else C_WHITE
        rows.append([
            Paragraph(str(row.get("task_id","")),  s["td"]),
            Paragraph(str(row.get("task_name","")), s["td"]),
            Paragraph(str(row.get("assigned_to","")), s["td"]),
            Paragraph(status, s["td"]),
            Paragraph(str(row.get("priority","")), s["td"]),
            Paragraph(str(row.get("start_date","")), s["td"]),
            Paragraph(str(row.get("end_date","")), s["td"]),
            Paragraph(f"{row.get('completion_percentage','')}%", s["td"]),
            Paragraph(str(row.get("notes","")), s["td"]),
        ])
        cmds += [
            ("BACKGROUND", (0,i),(2,i), bg),
            ("BACKGROUND", (4,i),(-1,i), bg),
            ("BACKGROUND", (3,i),(3,i), STATUS_BG.get(status.lower(), C_WHITE)),
        ]
    t = Table(rows, colWidths=COL_W)
    t.setStyle(TableStyle(cmds))
    return t


def _chart(excel_data: list[dict]) -> Drawing:
    tasks = [str(r.get("task_name",""))[:10] for r in excel_data]
    comp  = []
    for r in excel_data:
        val = str(r.get("completion_percentage", 0))
        comp.append(int(val) if val.isdigit() else 0)
        
    d = Drawing(420, 210)
    d.add(Rect(0,0,420,210, fillColor=C_GREY, strokeColor=C_BDR, strokeWidth=0.5))
    c = VerticalBarChart()
    c.x, c.y, c.width, c.height = 50, 35, 350, 145
    c.data = [comp]
    c.categoryAxis.categoryNames   = tasks
    c.categoryAxis.labels.angle    = 15
    c.categoryAxis.labels.dy       = -6
    c.categoryAxis.labels.fontSize = 7
    c.categoryAxis.labels.fontName = "Helvetica"
    c.valueAxis.valueMin           = 0
    c.valueAxis.valueMax           = 100
    c.valueAxis.valueStep          = 20
    c.valueAxis.labels.fontSize    = 7
    c.valueAxis.labels.fontName    = "Helvetica"
    c.bars[0].fillColor            = C_BLUE
    c.bars[0].strokeColor          = C_NAVY
    c.bars[0].strokeWidth          = 0.3
    c.groupSpacing                 = 5
    for i, val in enumerate(comp):
        if   val >= 80: c.bars[(0,i)].fillColor = C_GREEN
        elif val >= 40: c.bars[(0,i)].fillColor = colors.HexColor("#F59E0B")
        else:            c.bars[(0,i)].fillColor = colors.HexColor("#EF4444")
    d.add(c)
    d.add(String(210, 200, "Task Completion Overview (%)",
                 textAnchor="middle", fontSize=10,
                 fontName="Helvetica-Bold", fillColor=C_NAVY))
    return d


def _auto_summary(task: str, data: list[dict]) -> str:
    total   = len(data)
    done    = sum(1 for r in data if "done"     in str(r.get("status","")).lower())
    prog    = sum(1 for r in data if "progress" in str(r.get("status","")).lower())
    pending = total - done - prog
    
    comp_sum = 0
    for r in data:
        v = str(r.get("completion_percentage", 0))
        comp_sum += int(v) if v.isdigit() else 0
    avg = (comp_sum / total) if total else 0
    
    level   = "high" if avg >= 80 else "moderate" if avg >= 40 else "low"
    return (
        f"This automated report was generated for: <b>{task}</b>. "
        f"<b>{total}</b> task items were analysed — <b>{done}</b> completed, "
        f"<b>{prog}</b> in progress, <b>{pending}</b> pending. "
        f"Average completion: <b>{avg:.1f}%</b> ({level} overall project progress)."
    )


def generate_pdf(task: str, context: dict | None = None) -> str:
    """
    Generate a styled A4 PDF report and open it.
    Returns the absolute path to the saved PDF.

    Called by executor.py as:
        from actions.pdf import generate_pdf
        path = generate_pdf(task, context)
    """
    _ensure_output_dir()
    context    = context or {}
    excel_data = context.get("data", [])
    timestamp  = datetime.now().strftime("%d-%m-%Y_%H%M%S")
    filename   = os.path.join(OUTPUT_DIR, f"report_{timestamp}.pdf")

    doc = SimpleDocTemplate(
        filename, pagesize=A4,
        topMargin=1.9*cm, bottomMargin=1.8*cm,
        leftMargin=1.5*cm, rightMargin=1.5*cm,
        title="Automated Task Report",
        author="AI Desktop Workflow Agent",
    )
    s     = _styles()
    story = []

    story.append(Spacer(1, 0.5*cm))
    story.append(Paragraph("Automated Task Report", s["title"]))
    story.append(Paragraph(
        f"AI Desktop Workflow Agent &nbsp;|&nbsp; {datetime.now().strftime('%d %B %Y')}",
        s["sub"]))
    story.append(HRFlowable(width="100%", thickness=2, color=C_BLUE, spaceAfter=10))

    story.append(KeepTogether([Paragraph("Report Details", s["section"]),
                                _info_table(s, task)]))

    story.append(Paragraph("Executive Summary", s["section"]))
    story.append(Paragraph(
        _auto_summary(task, excel_data) if excel_data
        else "This report was automatically generated by the AI Desktop Workflow Agent.",
        s["body"]))

    if excel_data:
        story.append(KeepTogether([Paragraph("Task Data", s["section"]),
                                   _data_table(s, excel_data)]))
        story.append(Spacer(1, 0.3*cm))
        story.append(Paragraph("Performance Chart", s["section"]))
        story.append(_chart(excel_data))

    # Files section
    file_rows = []
    if context.get("excel"): file_rows.append(("Excel Report",  os.path.basename(context["excel"])))
    if context.get("doc"):   file_rows.append(("Word Document", os.path.basename(context["doc"])))
    file_rows.append(("PDF Report", os.path.basename(filename)))

    story.append(Paragraph("Generated Files", s["section"]))
    ftbl = Table([[Paragraph(a, s["lbl"]), Paragraph(b, s["val"])]
                  for a, b in file_rows], colWidths=[4*cm, 12.5*cm])
    ftbl.setStyle(TableStyle([
        ("BACKGROUND",     (0,0),(0,-1), C_BLUEL),
        ("ROWBACKGROUNDS", (1,0),(1,-1), [C_WHITE, C_GREY]),
        ("GRID",           (0,0),(-1,-1), 0.4, C_BDR),
        ("LEFTPADDING",    (0,0),(-1,-1), 8),
        ("RIGHTPADDING",   (0,0),(-1,-1), 8),
        ("TOPPADDING",     (0,0),(-1,-1), 5),
        ("BOTTOMPADDING",  (0,0),(-1,-1), 5),
    ]))
    story.append(ftbl)

    story.append(Spacer(1, 0.6*cm))
    story.append(HRFlowable(width="100%", thickness=0.5, color=C_BDR))
    story.append(Spacer(1, 0.2*cm))
    story.append(Paragraph(
        f"Auto-generated on {datetime.now().strftime('%d %b %Y at %H:%M')} "
        "by the AI Desktop Workflow Agent. Do not edit manually.",
        s["footer"]))

    doc.build(story, onFirstPage=_header_footer, onLaterPages=_header_footer)
    os.startfile(filename)
    print(f"PDF saved -> {filename}")
    return filename